version: '3'

services:
  blog-api:
    image: 'blog-api'
    build:
      context: .
    container_name: blog-api
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/blog-app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=blog-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres