spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
jwt:
  access-key: ${ACCESS_TOKEN_KEY_SECRET}
  refresh-key: ${REFRESH_TOKEN_KEY_SECRET}
  valid-duration: ${VALID_DURATION:5}
  refreshable-duration: ${REFRESHABLE-DURATION:15}
server:
  cookie:
    domain: ${DOMAIN_COOKIE_DEV}
    path: ${PATH_COOKIE_DEV}
