spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: 'swagger-ui-custom.html'
    operationsSorter: method
cloudinary:
  cloud-name:
  api-key:
  api-secret:
jwt:
  access-key:
  refresh-key:
server:
  cookie:
    domain:
    path: